### ISSUE TITLE
Invisible ReCaptcha

### ISSUE THREAD

**Issue by alexkazik** [ncaq/yesod-recaptcha2#3]
Here is a first draft to add Invisible ReCaptcha:

New methods:
````
mReCaptchaInvisible :: YesodReCaptcha site => MForm (HandlerFor site) (FormResult ())
mReCaptchaInvisible = fst <$> mReCaptcha

reCaptchaInvisible :: YesodReCaptcha site => AForm (HandlerFor site) ()
reCaptchaInvisible = formToAForm ((,[]) <$> mReCaptchaInvisible)

reCaptchaInvisibleButton :: YesodReCaptcha site => Maybe Text -> HandlerFor site (Text, WidgetFor site (), [(Text, Text)])
reCaptchaInvisibleButton mIdent = do
  mReCaptchaLanguage <- reCaptchaLanguage
  siteKey <- reCaptchaSiteKey
  ident <- maybe newIdent return mIdent
  let
    scriptName = "reCaptchaOnSubmit_" <> ident
  let
    widget = do
      case mReCaptchaLanguage of
        Nothing ->
          addScriptRemote "https://www.google.com/recaptcha/api.js"
        Just hl ->
          addScriptRemote $ "https://www.google.com/recaptcha/api.js?hl=" <> hl
      [whamlet|<script>function #{scriptName} (token) { document.getElementById("#{ident}").submit(); } |]
  return
    ( ident
    , widget
    , [("data-sitekey", siteKey), ("data-callback", scriptName)]
    )
````

How to use:
where you render the form:
`(formIdent, reCaptchaWidget, reCaptchaButtonAttributes) <- reCaptchaInvisibleButton Nothing`
You can replace Nothing with Just "id" if the form has already an id, otherwise a new one will be generated.
In the form:
1. the form itself needs a id: `<form ##{formIdent} method=post action=@{route} enctype=#{enctype}>`
2. the button requires a special class and attributes, minimal: `<button .g-recaptcha *{reCaptchaButtonAttributes}>`
3. add the widget `^{reCaptchaWidget}` (somewhere)

This is the easiest way I could figure out.

The AForm is untested! (the MForm works like a charm.)

Feel free to add it if you like.

**Comment by ncaq** [comment]
Good.
Can you create pull request?

**Comment by alexkazik** [comment]
I can try it. 

Should I add it as above or move the check functionality to mReCaptchaInvisible and mReCaptcha depends on it?

Btw. I would have preferred a version of mReCaptcha which only returns one FieldView and not a list of one - I can add mReCaptcha' which does that? (since changing will break)

**Comment by ncaq** [comment]
I do not dislike having multiple APIs.
Why do not we do fine-tuning such as naming after actually making a pull request?
For the moment I have not made a design image.
